### ISSUE TITLE
[Bug] ApplySystem uses network when it shouldn't

### ISSUE THREAD

**Issue by notdanilo** [magicblock-labs/bolt#109]
**Describe the bug**
`ApplySystem` should simply return an instruction while it internally uses a provider.

```typescript
provider.ts:91 Uncaught (in promise) Error: Provider local is not available on browser.
    at AnchorProvider.local (provider.ts:91:1)
    at getProvider (provider.ts:416:1)
    at new Program (index.ts:281:1)
    at transactions.ts:333:1
    at step (index.ts:87:1)
    at Object.next (index.ts:87:1)
    at index.ts:87:1
    at new Promise (<anonymous>)
    at __webpack_modules__../node_modules/@magicblock-labs/bolt-sdk/lib/world/transactions.js.__awaiter (index.ts:87:1)
    at createApplySystemInstruction (transactions.ts:331:1)
```

**To Reproduce**
Call `ApplySystem`

**Expected behavior**
It should simply return the Instruction and a Transaction with the Instruction

**Comment by notdanilo** [comment]
I am no longer considering it a bug as we can use setProvider as intended by anchor to make ApplySystem work (it relies on getProvider)

**Comment by notdanilo** [comment]
But it makes sense for me for functions to create instructions to be always sync without the need to interact with the network. But to make it happen, some API redesign might be necessary
